drop table FDB_AGID_AXSID cascade constraints/
drop table FDB_AHFSCLASS_DRUGCONCEPT cascade constraints/
drop table FDB_AHFSCLASSIFICATION_DRUGS cascade constraints/
drop table FDB_AHFSCLASSIFICATION_LINK cascade constraints/
drop table FDB_ALLERGEN_HICSEQNO cascade constraints/
drop table FDB_ALLERGENGROUP cascade constraints/
drop table FDB_ALLERGENGROUP_II cascade constraints/
drop table FDB_ALLERGENGROUPSEARCH cascade constraints/
drop table FDB_ALLERGENGROUPSEARCH_II cascade constraints/
drop table FDB_ALLERGENPICKLIST cascade constraints/
drop table FDB_ALLERGENPICKLISTSEARCH cascade constraints/
drop table FDB_ALLERGENS cascade constraints/
drop table FDB_ALLERGENS_II cascade constraints/
drop table FDB_ALLERGYCROSSSENSITIVITY cascade constraints/
drop table FDB_CLASS_AHFS cascade constraints/
drop table FDB_CLASS_AHFSSEARCH cascade constraints/
drop table FDB_CLASS_FDB cascade constraints/
drop table FDB_CLASS_FDBSEARCH cascade constraints/
drop table FDB_CLASSIFICATION_AHFS cascade constraints/
drop table FDB_CLASSIFICATION_AHFSSEARCH cascade constraints/
drop table FDB_CLASSIFICATION_ETC cascade constraints/
drop table FDB_CLASSIFICATION_ETCSEARCH cascade constraints/
drop table FDB_CLASSIFICATION_EXT cascade constraints/
drop table FDB_CLASSIFICATION_EXTSEARCH cascade constraints/
drop table FDB_CLASSIFICATION_FDB cascade constraints/
drop table FDB_CLASSIFICATION_FDBSEARCH cascade constraints/
drop table FDB_CODEDEFINITION cascade constraints/
drop table FDB_COMPOUND cascade constraints/
drop table FDB_COMPOUND_RTGEN cascade constraints/
drop table FDB_COMPOUNDSEARCH cascade constraints/
drop table FDB_CONCEPT_IISURVEY cascade constraints/
drop table FDB_CONCEPT_PEMDRUGLINK cascade constraints/
drop table FDB_CONCEPT_WITHINACTIVES cascade constraints/
drop table FDB_CUSTOM_ALLERGENPICKLIST cascade constraints/
drop table FDB_CUSTOM_ALLERGENPICKLSTSRCH cascade constraints/
drop table FDB_CUSTOM_ATTRIBUTENAMES cascade constraints/
drop table FDB_CUSTOM_ATTRIBUTEVALUES cascade constraints/
drop table FDB_CUSTOM_CLASS cascade constraints/
drop table FDB_CUSTOM_CLASS_DRUGCONCEPT cascade constraints/
drop table FDB_CUSTOM_CLASS_SEARCH cascade constraints/
drop table FDB_CUSTOM_DDIM cascade constraints/
drop table FDB_CUSTOM_DDIMDRUGLINKCAT cascade constraints/
drop table FDB_CUSTOM_DDIMINTERACTION cascade constraints/
drop table FDB_CUSTOM_DDIMSTRINGS cascade constraints/
drop table FDB_CUSTOM_DOSERANGECHECK cascade constraints/
drop table FDB_CUSTOM_DOSING cascade constraints/
drop table FDB_CUSTOM_DOSINGNEO cascade constraints/
drop table FDB_CUSTOM_DRUGMAPPING cascade constraints/
drop table FDB_CUSTOM_DTCAT cascade constraints/
drop table FDB_CUSTOM_INDICATION cascade constraints/
drop table FDB_CUSTOM_INTERACTCATEGORY cascade constraints/
drop table FDB_CUSTOM_MONOGRAPH cascade constraints/
drop table FDB_CUSTOM_MSG_CATDEF cascade constraints/
drop table FDB_CUSTOM_MSG_DEF cascade constraints/
drop table FDB_CUSTOM_MSG_LINK cascade constraints/
drop table FDB_CUSTOM_MSG_TEXT cascade constraints/
drop table FDB_CUSTOM_PACKAGEDDRUGPRICING cascade constraints/
drop table FDB_DAMSCREEN cascade constraints/
drop table FDB_DAMSCREEN_II cascade constraints/
drop table FDB_DAMSCREENINFO cascade constraints/
drop table FDB_DAMSCREENINFO_II cascade constraints/
drop table FDB_DDCM cascade constraints/
drop table FDB_DDCMDRUGLINK cascade constraints/
drop table FDB_DDIM_CATSEVERITIES cascade constraints/
drop table FDB_DDIMDRUGLINK cascade constraints/
drop table FDB_DDIMINACTIVEDRUGLINK cascade constraints/
drop table FDB_DDIMINTERACTION cascade constraints/
drop table FDB_DFIMDRUGLINK cascade constraints/
drop table FDB_DFIMINTERACTION cascade constraints/
drop table FDB_DISCLAIMER cascade constraints/
drop table FDB_DISCREEN cascade constraints/
drop table FDB_DISPENSABLE cascade constraints/
drop table FDB_DISPENSABLE_IMAGE cascade constraints/
drop table FDB_DISPENSABLE_LABELER cascade constraints/
drop table FDB_DOSEFORM cascade constraints/
drop table FDB_DOSERANGECHECK cascade constraints/
drop table FDB_DOSEROUTE cascade constraints/
drop table FDB_DOSETYPE cascade constraints/
drop table FDB_DOSEUNITSCONVERSION cascade constraints/
drop table FDB_DOSEUNITSTYPE cascade constraints/
drop table FDB_DOSING cascade constraints/
drop table FDB_DOSINGNEO cascade constraints/
drop table FDB_DRCNEO cascade constraints/
drop table FDB_DRUG_MONOGRAPH_EXT cascade constraints/
drop table FDB_DRUG_PCM cascade constraints/
drop table FDB_DRUG_PLBLW cascade constraints/
drop table FDB_DRUG_RTGENID cascade constraints/
drop table FDB_DRUGNAME cascade constraints/
drop table FDB_DRUGVALIDATION cascade constraints/
drop table FDB_DTDRUGLINK cascade constraints/
drop table FDB_DUPLICATETHERAPY cascade constraints/
drop table FDB_DXID_RELATEDDXID cascade constraints/
drop table FDB_ETCLASSIFICATION_DRUGS cascade constraints/
drop table FDB_ETCLASSIFICATION_LINK cascade constraints/
drop table FDB_EXTCLASSIFICATION_DRUGS cascade constraints/
drop table FDB_EXTCLASSIFICATION_IDRUGS cascade constraints/
drop table FDB_EXTCLASSIFICATION_LINK cascade constraints/
drop table FDB_EXTVOCAB_RELATEDDXID cascade constraints/
drop table FDB_FDBCLASS_DRUGCONCEPT cascade constraints/
drop table FDB_FDBCLASSIFICATION_DRUGS cascade constraints/
drop table FDB_FDBCLASSIFICATION_LINK cascade constraints/
drop table FDB_GCNSEQNO_PCM cascade constraints/
drop table FDB_GCNSEQNO_PEM cascade constraints/
drop table FDB_GCNSEQNO_PLBLW cascade constraints/
drop table FDB_GENERIC_DISPENSABLE cascade constraints/
drop table FDB_GENERIC_DISPENSABLE_TEMP cascade constraints/
drop table FDB_GENERIC_DISPSEARCH cascade constraints/
drop table FDB_GENERIC_DRUGNAME cascade constraints/
drop table FDB_GENERIC_DRUGNAMESEARCH cascade constraints/
drop table FDB_GENERIC_ROUTEDDFDRUG cascade constraints/
drop table FDB_GENERIC_ROUTEDDFDRUGSEARCH cascade constraints/
drop table FDB_GENERIC_ROUTEDDRUG cascade constraints/
drop table FDB_GENERIC_ROUTEDDRUG_TEMP cascade constraints/
drop table FDB_GENERIC_ROUTEDDRUGSEARCH cascade constraints/
drop table FDB_GENERICDOSEFORM cascade constraints/
drop table FDB_HICL_HICSEQNO cascade constraints/
drop table FDB_HICSEQNO_AGID cascade constraints/
drop table FDB_HICSEQNO_AXSID cascade constraints/
drop table FDB_HICSEQNO_BASEINGREDIENT cascade constraints/
drop table FDB_IMAGE cascade constraints/
drop table FDB_IMPCOLORPALETTE cascade constraints/
drop table FDB_IMPDESCCOLORS cascade constraints/
drop table FDB_IMPRINT cascade constraints/
drop table FDB_IMPRINTCOLORS cascade constraints/
drop table FDB_IMPRINTDESCRIPTION cascade constraints/
drop table FDB_IMPRINTDESCTEXT cascade constraints/
drop table FDB_IMPRINTSHAPE cascade constraints/
drop table FDB_IMPSHAPEPALETTE cascade constraints/
drop table FDB_IND cascade constraints/
drop table FDB_INDDRUGLINK cascade constraints/
drop table FDB_INGREDIENT cascade constraints/
drop table FDB_INGREDIENTSEARCH cascade constraints/
drop table FDB_IVM cascade constraints/
drop table FDB_IVM_COMPDESC cascade constraints/
drop table FDB_IVM_MFGDESC cascade constraints/
drop table FDB_IVM_REMARKLINK cascade constraints/
drop table FDB_IVM_REMARKS cascade constraints/
drop table FDB_IVM_TESTCOMPCOUNT cascade constraints/
drop table FDB_IVM_TPN_INGRED cascade constraints/
drop table FDB_LABELER cascade constraints/
drop table FDB_LANGUAGE cascade constraints/
drop table FDB_MANUFDRUG cascade constraints/
drop table FDB_MANUFDRUGEXTID cascade constraints/
drop table FDB_MANUFDRUGPROPNAME cascade constraints/
drop table FDB_MANUFDRUGPROPVALUE cascade constraints/
drop table FDB_MANUFDRUGSEARCH cascade constraints/
drop table FDB_MEDCOND cascade constraints/
drop table FDB_MEDCOND_HIERARCHY cascade constraints/
drop table FDB_MEDCONDEXT_HIERARCHY cascade constraints/
drop table FDB_MEDCONDEXTVOCAB cascade constraints/
drop table FDB_MEDCONDEXTVOCABLINK cascade constraints/
drop table FDB_MEDCONDEXTVOCABSEARCH cascade constraints/
drop table FDB_MEDCONDSEARCH cascade constraints/
drop table FDB_MEDCONDSEARCHFML cascade constraints/
drop table FDB_MEDCONDXREF cascade constraints/
drop table FDB_MINMAXDOSING cascade constraints/
drop table FDB_MINMAXWARNINGS cascade constraints/
drop table FDB_MNID_HICL cascade constraints/
drop table FDB_MONOGRAPH_DDIM cascade constraints/
drop table FDB_MONOGRAPH_DFIM cascade constraints/
drop table FDB_MONOGRAPH_EXT cascade constraints/
drop table FDB_MONOGRAPH_PEM cascade constraints/
drop table FDB_PACKAGEDDRUG cascade constraints/
drop table FDB_PACKAGEDDRUGCURRENTPRICING cascade constraints/
drop table FDB_PACKAGEDDRUGPRICINGHISTORY cascade constraints/
drop table FDB_PATIENTCOUNSELING cascade constraints/
drop table FDB_PEDIATRICWEIGHT cascade constraints/
drop table FDB_PLBLWARN_VENDCODE cascade constraints/
drop table FDB_PLBLWARNINGS cascade constraints/
drop table FDB_POEM cascade constraints/
drop table FDB_POEM_ADMINRATES cascade constraints/
drop table FDB_POEM_DEFAULT cascade constraints/
drop table FDB_POEM_DOSEFORMUNITS cascade constraints/
drop table FDB_POEM_ORDERSTRING cascade constraints/
drop table FDB_POEM_ORDERSTRING_ADDLTEXT cascade constraints/
drop table FDB_POEM_UNITS cascade constraints/
drop table FDB_POEMTEXT cascade constraints/
drop table FDB_PRECGERI cascade constraints/
drop table FDB_PRECGERI_DRUGLINK cascade constraints/
drop table FDB_PRECGERI_GCNSEQNO cascade constraints/
drop table FDB_PRECGERI_RTDFGEN cascade constraints/
drop table FDB_PRECGERI_RTGEN cascade constraints/
drop table FDB_PRECLACT cascade constraints/
drop table FDB_PRECLACT_DRUGLINK cascade constraints/
drop table FDB_PRECLACT_GCNSEQNO cascade constraints/
drop table FDB_PRECLACT_RTDFGEN cascade constraints/
drop table FDB_PRECLACT_RTGEN cascade constraints/
drop table FDB_PRECPEDI cascade constraints/
drop table FDB_PRECPEDI_DRUGLINK cascade constraints/
drop table FDB_PRECPEDI_GCNSEQNO cascade constraints/
drop table FDB_PRECPEDI_RTDFGEN cascade constraints/
drop table FDB_PRECPEDI_RTGEN cascade constraints/
drop table FDB_PRECPREG cascade constraints/
drop table FDB_PRECPREG_DRUGLINK cascade constraints/
drop table FDB_PRECPREG_GCNSEQNO cascade constraints/
drop table FDB_PRECPREG_RTDFGEN cascade constraints/
drop table FDB_PRECPREG_RTGEN cascade constraints/
drop table FDB_RDFMID_RTDFGENID cascade constraints/
drop table FDB_REFITEM cascade constraints/
drop table FDB_REFITEM_ATTRIBUTENAMES cascade constraints/
drop table FDB_REFITEM_ATTRIBUTEVALUES cascade constraints/
drop table FDB_REFITEM_MSG_CATDEF cascade constraints/
drop table FDB_REFITEM_MSG_DEF cascade constraints/
drop table FDB_REFITEM_MSG_LINK cascade constraints/
drop table FDB_REFITEM_MSG_TEXT cascade constraints/
drop table FDB_REFITEM_SEARCH cascade constraints/
drop table FDB_REGPACKAGED cascade constraints/
drop table FDB_REGPACKAGEDEXTID cascade constraints/
drop table FDB_REGPACKAGEDPROPNAME cascade constraints/
drop table FDB_REGPACKAGEDPROPVALUE cascade constraints/
drop table FDB_REGPACKAGEDSEARCH cascade constraints/
drop table FDB_REPLACEMENTALLERGENGROUPS cascade constraints/
drop table FDB_REPLACEMENTDRUGS cascade constraints/
drop table FDB_REPLACEMENTDXIDS cascade constraints/
drop table FDB_REPLACEMENTINGREDIENTS cascade constraints/
drop table FDB_RMID_RTGENID cascade constraints/
drop table FDB_ROUTE cascade constraints/
drop table FDB_ROUTEDDFDRUG cascade constraints/
drop table FDB_ROUTEDDRUG cascade constraints/
drop table FDB_RTGENID_GENERICRMID cascade constraints/
drop table FDB_SETTINGS cascade constraints/
drop table FDB_SIDE cascade constraints/
drop table FDB_SIDEDRUGLINK cascade constraints/
drop table FDB_SUBSET_DRUGVALUES cascade constraints/
drop table FDB_SUBSET_SET cascade constraints/
drop table FDB_SUBSET_SITE cascade constraints/
drop table FDB_USER_DDIM cascade constraints/
drop table FDB_USER_DDIMDRUGLINK_CATEGORY cascade constraints/
drop table FDB_USER_DDIMINTERACTION cascade constraints/
drop table FDB_USER_INTERACTION_CATEGORY cascade constraints/
drop table FDB_VERSION cascade constraints/
drop table CT_VERSION cascade constraints/
